services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tit_proy
      POSTGRES_USER: tit_user
      POSTGRES_PASSWORD: tit_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # nuevo 
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    env_file: .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./app/uploads:/app/app/uploads:rw

volumes:
  pgdata:
