"""allow null on all dte_details

Revision ID: 237debe40bc9
Revises: 7a218013ea92
Create Date: 2025-10-13 00:24:02.219488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237debe40bc9'
down_revision: Union[str, None] = '7a218013ea92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dte_details', 'nro_linea',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dte_details', 'tipo_codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('dte_details', 'nombre_item',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('dte_details', 'cantidad',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    op.alter_column('dte_details', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    op.alter_column('dte_details', 'monto_item',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dte_details', 'monto_item',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('dte_details', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)
    op.alter_column('dte_details', 'cantidad',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)
    op.alter_column('dte_details', 'nombre_item',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('dte_details', 'tipo_codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('dte_details', 'nro_linea',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
