"""uniq detalle por header+linea

Revision ID: 3543054a7163
Revises: 03e377b98230
Create Date: 2025-10-15 21:37:45.810030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3543054a7163'
down_revision: Union[str, None] = '03e377b98230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_dq_results', table_name='dq_results')
    op.drop_table('dq_results')
    op.drop_index('ix_run_logs_started_at', table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_table('etl_state')
    op.drop_index('ix_audit_logs_ts', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.alter_column('dq_rules', 'code',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('dq_rules', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('dq_rules', 'entity',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_dq_rules_id'), 'dq_rules', ['id'], unique=False)
    op.add_column('dq_violations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('dq_violations', 'run_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=64),
               nullable=True)
    op.alter_column('dq_violations', 'entity',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('dq_violations', 'message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index('ix_dq_violations_entity_entity_id', 'dq_violations', ['entity', 'entity_id'], unique=False)
    op.create_index(op.f('ix_dq_violations_id'), 'dq_violations', ['id'], unique=False)
    op.create_index(op.f('ix_dq_violations_rule_id'), 'dq_violations', ['rule_id'], unique=False)
    op.drop_constraint('dq_violations_rule_id_fkey', 'dq_violations', type_='foreignkey')
    op.create_foreign_key(None, 'dq_violations', 'dq_rules', ['rule_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint('uq_dte_details_header_line', 'dte_details', ['header_id', 'nro_linea'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dte_details_header_line', 'dte_details', type_='unique')
    op.drop_constraint(None, 'dq_violations', type_='foreignkey')
    op.create_foreign_key('dq_violations_rule_id_fkey', 'dq_violations', 'dq_rules', ['rule_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_dq_violations_rule_id'), table_name='dq_violations')
    op.drop_index(op.f('ix_dq_violations_id'), table_name='dq_violations')
    op.drop_index('ix_dq_violations_entity_entity_id', table_name='dq_violations')
    op.alter_column('dq_violations', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('dq_violations', 'entity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('dq_violations', 'run_id',
               existing_type=sa.String(length=64),
               type_=sa.UUID(),
               nullable=False)
    op.drop_column('dq_violations', 'created_at')
    op.drop_index(op.f('ix_dq_rules_id'), table_name='dq_rules')
    op.alter_column('dq_rules', 'entity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('dq_rules', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('dq_rules', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('ix_audit_logs_ts', 'audit_logs', ['ts'], unique=False)
    op.create_table('etl_state',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='etl_state_pkey'),
    comment='Key-Value para watermarks (p.ej. last_fch_emis, last_id)'
    )
    op.create_table('run_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'RUNNING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rows_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_out', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='run_logs_pkey'),
    sa.UniqueConstraint('run_id', name='run_logs_run_id_key')
    )
    op.create_index('ix_run_logs_started_at', 'run_logs', ['started_at'], unique=False)
    op.create_table('dq_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['dq_rules.id'], name='dq_results_rule_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dq_results_pkey')
    )
    op.create_index('uq_dq_results', 'dq_results', ['run_id', 'rule_id'], unique=True)
    # ### end Alembic commands ###
