"""add dq indexes

Revision ID: 46528ffdfb03
Revises: 3543054a7163
Create Date: 2025-10-15 22:47:18.642485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46528ffdfb03'
down_revision: Union[str, None] = '3543054a7163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dq_violations_run_id', 'dq_violations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dq_violations_run_id', table_name='dq_violations')
    # ### end Alembic commands ###
