"""expand dte_details fields

Revision ID: 4900fb6e11d7
Revises: c660fdcfb078
Create Date: 2025-10-11 03:21:32.820041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4900fb6e11d7'
down_revision: Union[str, None] = 'c660fdcfb078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_details', sa.Column('precio_unitario', sa.Numeric(precision=18, scale=6), nullable=False))
    op.drop_column('dte_details', 'precio_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_details', sa.Column('precio_unit', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False))
    op.drop_column('dte_details', 'precio_unitario')
    # ### end Alembic commands ###
