"""add nro_linea to dte_details

Revision ID: 6051573d871e
Revises: f16221958442
Create Date: 2025-10-11 02:59:22.453425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6051573d871e'
down_revision: Union[str, None] = 'f16221958442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_details', sa.Column('nro_linea', sa.Integer(), nullable=False))
    op.drop_column('dte_details', 'n_linea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_details', sa.Column('n_linea', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('dte_details', 'nro_linea')
    # ### end Alembic commands ###
