"""add dq_health table

Revision ID: 8b3fdc6f616c
Revises: e9879d193bfa
Create Date: 2025-10-29 11:30:50.875304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3fdc6f616c'
down_revision: Union[str, None] = 'e9879d193bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dq_health',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('violations_total', sa.Integer(), nullable=False),
    sa.Column('headers', sa.Integer(), nullable=False),
    sa.Column('details', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dq_health')
    # ### end Alembic commands ###
