"""expand dte_details fields

Revision ID: c660fdcfb078
Revises: 6051573d871e
Create Date: 2025-10-11 03:20:30.522384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c660fdcfb078'
down_revision: Union[str, None] = '6051573d871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_details', sa.Column('tipo_codigo', sa.String(length=20), nullable=False))
    op.add_column('dte_details', sa.Column('nombre_item', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dte_details', 'nombre_item')
    op.drop_column('dte_details', 'tipo_codigo')
    # ### end Alembic commands ###
