"""dte tables

Revision ID: c73db0b616f6
Revises: 3c12429e1559
Create Date: 2025-10-10 17:34:09.948290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73db0b616f6'
down_revision: Union[str, None] = '3c12429e1559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dte_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('tipo_dte', sa.String(length=10), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('rut_emisor', sa.String(length=16), nullable=False),
    sa.Column('rznsoc_emisor', sa.String(length=200), nullable=False),
    sa.Column('rut_receptor', sa.String(length=16), nullable=False),
    sa.Column('rznsoc_receptor', sa.String(length=200), nullable=False),
    sa.Column('mnt_neto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('mnt_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dte_headers_fecha_emision'), 'dte_headers', ['fecha_emision'], unique=False)
    op.create_index(op.f('ix_dte_headers_file_id'), 'dte_headers', ['file_id'], unique=False)
    op.create_index(op.f('ix_dte_headers_folio'), 'dte_headers', ['folio'], unique=False)
    op.create_index(op.f('ix_dte_headers_id'), 'dte_headers', ['id'], unique=False)
    op.create_index(op.f('ix_dte_headers_mnt_total'), 'dte_headers', ['mnt_total'], unique=False)
    op.create_index(op.f('ix_dte_headers_rut_emisor'), 'dte_headers', ['rut_emisor'], unique=False)
    op.create_index(op.f('ix_dte_headers_rut_receptor'), 'dte_headers', ['rut_receptor'], unique=False)
    op.create_index(op.f('ix_dte_headers_tipo_dte'), 'dte_headers', ['tipo_dte'], unique=False)
    op.create_table('dte_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('n_linea', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('precio_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('monto_item', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['header_id'], ['dte_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dte_details_header_id'), 'dte_details', ['header_id'], unique=False)
    op.create_index(op.f('ix_dte_details_monto_item'), 'dte_details', ['monto_item'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dte_details_monto_item'), table_name='dte_details')
    op.drop_index(op.f('ix_dte_details_header_id'), table_name='dte_details')
    op.drop_table('dte_details')
    op.drop_index(op.f('ix_dte_headers_tipo_dte'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_rut_receptor'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_rut_emisor'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_mnt_total'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_id'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_folio'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_file_id'), table_name='dte_headers')
    op.drop_index(op.f('ix_dte_headers_fecha_emision'), table_name='dte_headers')
    op.drop_table('dte_headers')
    # ### end Alembic commands ###
