"""unique dte header key

Revision ID: c8a4f2edf326
Revises: 237debe40bc9
Create Date: 2025-10-13 19:17:53.989241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a4f2edf326'
down_revision: Union[str, None] = '237debe40bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dte_headers_fecha', 'dte_headers', ['fecha_emision'], unique=False)
    op.create_unique_constraint('uq_dte_headers_tipo_folio_emisor', 'dte_headers', ['tipo_dte', 'folio', 'rut_emisor'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dte_headers_tipo_folio_emisor', 'dte_headers', type_='unique')
    op.drop_index('ix_dte_headers_fecha', table_name='dte_headers')
    # ### end Alembic commands ###
