"""add razon_social cols to dte_headers

Revision ID: f16221958442
Revises: c73db0b616f6
Create Date: 2025-10-11 02:11:56.833405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16221958442'
down_revision: Union[str, None] = 'c73db0b616f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_headers', sa.Column('razon_social_emisor', sa.String(length=255), nullable=True))
    op.add_column('dte_headers', sa.Column('razon_social_receptor', sa.String(length=255), nullable=True))
    op.drop_column('dte_headers', 'rznsoc_emisor')
    op.drop_column('dte_headers', 'rznsoc_receptor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dte_headers', sa.Column('rznsoc_receptor', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('dte_headers', sa.Column('rznsoc_emisor', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('dte_headers', 'razon_social_receptor')
    op.drop_column('dte_headers', 'razon_social_emisor')
    # ### end Alembic commands ###
